export const DUMMY_JOBS = [
  {
    id: 'job-fan-wiring',
    serviceId: 'electrician',
    title: 'Fix ceiling fan wiring',
    description: 'Bedroom fan stopped after a power cut. Wiring and switchboard need a check.',
    price: 450,
    distanceKm: 1.2,
    area: 'Teliarganj',
    poster: { name: 'Ritika Sharma', rating: 4.5 },
  },
  {
    id: 'job-2bhk-shift',
    serviceId: 'movers',
    title: 'Shift a 2BHK to Civil Lines',
    description: 'Packing, loading and unloading. Two beds, a fridge and about 20 boxes.',
    price: 6500,
    distanceKm: 3.8,
    area: 'Allahpur',
    poster: { name: 'Anil Verma', rating: 4 },
  },
  {
    id: 'job-sink-leak',
    serviceId: 'plumber',
    title: 'Kitchen sink leakage',
    description: 'Water dripping under the sink cabinet. Pipe joint probably needs replacing.',
    price: 350,
    distanceKm: 0.8,
    area: 'Mumfordganj',
    poster: { name: 'Sana Khan', rating: 5 },
  },
  {
    id: 'job-bookshelf',
    serviceId: 'carpenter',
    title: 'Build a wooden bookshelf',
    description: 'Five-shelf wall unit, about 6 ft tall. Wood will be provided.',
    price: 2800,
    distanceKm: 2.5,
    area: 'Georgetown',
    poster: { name: 'Pradeep Mishra', rating: 3.5 },
  },
  {
    id: 'job-diwali-clean',
    serviceId: 'cleaning',
    title: 'Deep clean a 3BHK before Diwali',
    description: 'Kitchen, bathrooms, fans and windows. Team of two preferred.',
    price: 2200,
    distanceKm: 4.1,
    area: 'Civil Lines',
    poster: { name: 'Meena Gupta', rating: 4.5 },
  },
  {
    id: 'job-room-paint',
    serviceId: 'painter',
    title: 'Paint one bedroom',
    description: 'Walls and ceiling, 12 x 14 ft room. Paint colour already chosen.',
    price: 4000,
    distanceKm: 1.9,
    area: 'Katra',
    poster: { name: 'Rohit Yadav', rating: 4 },
  },
];
